// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const FileBrowser: typeof import('/Users/claudius/openstore/apps/extension/components/FileBrowser').FileBrowser
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const Select: typeof import('/Users/claudius/openstore/apps/extension/components/Select').Select
  const TrpcError: typeof import('/Users/claudius/openstore/apps/extension/utils/api').TrpcError
  const activeWorkspaceSlugStore: typeof import('/Users/claudius/openstore/apps/extension/utils/storage').activeWorkspaceSlugStore
  const blobToBase64: typeof import('/Users/claudius/openstore/apps/extension/utils/api').blobToBase64
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const downloadAsBlob: typeof import('/Users/claudius/openstore/apps/extension/utils/api').downloadAsBlob
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getActiveWorkspaceSlug: typeof import('/Users/claudius/openstore/apps/extension/utils/storage').getActiveWorkspaceSlug
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isSignedIn: typeof import('/Users/claudius/openstore/apps/extension/utils/storage').isSignedIn
  const onMessage: typeof import('/Users/claudius/openstore/apps/extension/utils/messaging').onMessage
  const probeSession: typeof import('/Users/claudius/openstore/apps/extension/utils/api').probeSession
  const sendMessage: typeof import('/Users/claudius/openstore/apps/extension/utils/messaging').sendMessage
  const setActiveWorkspaceSlug: typeof import('/Users/claudius/openstore/apps/extension/utils/storage').setActiveWorkspaceSlug
  const setSignedIn: typeof import('/Users/claudius/openstore/apps/extension/utils/storage').setSignedIn
  const signedInStore: typeof import('/Users/claudius/openstore/apps/extension/utils/storage').signedInStore
  const storage: typeof import('wxt/utils/storage').storage
  const trpcMutation: typeof import('/Users/claudius/openstore/apps/extension/utils/api').trpcMutation
  const trpcQuery: typeof import('/Users/claudius/openstore/apps/extension/utils/api').trpcQuery
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const webHost: typeof import('/Users/claudius/openstore/apps/extension/utils/web-host').webHost
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { FileBrowserProps } from '/Users/claudius/openstore/apps/extension/components/FileBrowser'
  import('/Users/claudius/openstore/apps/extension/components/FileBrowser')
  // @ts-ignore
  export type { SelectOption, SelectProps } from '/Users/claudius/openstore/apps/extension/components/Select'
  import('/Users/claudius/openstore/apps/extension/components/Select')
  // @ts-ignore
  export type { TrpcError } from '/Users/claudius/openstore/apps/extension/utils/api'
  import('/Users/claudius/openstore/apps/extension/utils/api')
  // @ts-ignore
  export type { Workspace, FolderRow, FileRow, Breadcrumb, ApiResult } from '/Users/claudius/openstore/apps/extension/utils/messaging'
  import('/Users/claudius/openstore/apps/extension/utils/messaging')
}
